steps:
- name: 'maven-build'  # Назва першого кроку
  entrypoint: 'mvn'
  args: ['clean', 'install', '-DskipTests']
- name: 'spring-boot-run'  # Назва другого кроку
  entrypoint: 'mvn'
  args: ['spring-boot:run']

